server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: item
  main:
    allow-bean-definition-overriding: true
  mvc:
    static-path-pattern: /static/**
#Feign连接超时
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

  #rabbitmq:
  #  host: 192.168.25.138
# 生成静态页的位置
pagepath: D:/idea/Workspaces/sharkshopping/drunk-parent/drunk-web/drunk-web-item/src/main/resources/templates/items