spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
              allowedOrigins: "*" #跨域处理 允许所有的域
              allowedMethods: # 支持的方法
                - GET
                - POST
                - PUT
                - DELETE
      routes:
           - id: drunk_goods_route
             uri: lb://goods
             predicates:
             #- Host=cloud.drunk.com**
             - Path=/brand/**
             filters:
             #配置路由前缀
             #- PrefixPath=/brand
                 #去掉第一个路径前缀
               #- StripPrefix=1
               - name: RequestRateLimiter #请求数限流
                 args:
                   key-resolver: "#{@ipKeyResolver}"
                   redis-rate-limiter.replenishRate: 1   #每秒执行请求数，令牌桶填充速率
                   redis-rate-limiter.burstCapacity: 1   #令牌桶容量，一秒内完成最大请求数
           - id: drunk_user_route
             uri: lb://user
             predicates:
             - Path=/user/**,/address/**
             filters:
               - name: RequestRateLimiter #请求数限流
                 args:
                   key-resolver: "#{@ipKeyResolver}"
                   redis-rate-limiter.replenishRate: 1   #每秒执行请求数，令牌桶填充速率
                   redis-rate-limiter.burstCapacity: 1   #令牌桶容量，一秒内完成最大请求数
           - id: drunk_oauth_route
             uri: lb://user-auth
             predicates:
             - Path=/oauth/**,/drunk/**,/static/**
             filters:
               - name: RequestRateLimiter #请求数限流
                 args:
                   key-resolver: "#{@ipKeyResolver}"
                   redis-rate-limiter.replenishRate: 10   #每秒执行请求数，令牌桶填充速率
                   redis-rate-limiter.burstCapacity: 10   #令牌桶容量，一秒内完成最大请求数
           - id: drunk_order_route
             uri: lb://order
             predicates:
             - Path=/order/**,/cart/**
             filters:
               - name: RequestRateLimiter #请求数限流
                 args:
                   key-resolver: "#{@ipKeyResolver}"
                   redis-rate-limiter.replenishRate: 1   #每秒执行请求数，令牌桶填充速率
                   redis-rate-limiter.burstCapacity: 1   #令牌桶容量，一秒内完成最大请求数
           - id: drunk_pay_route
             uri: lb://pay
             predicates:
             - Path=/weixin/pay/**
           - id: drunk_seckill_route
             uri: lb://seckill
             predicates:
             - Path=/seckillGoods/**,/seckillOrder/**
  #redis配置
  redis:
    host: 192.168.120.132
    port: 6379
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true